#!/usr/bin/env python3
"""
StepMania Generator v3.0 (Simplified Orchestrator)
Orchestrates the chart generation pipeline for StepMania starting from an existing .sm file.

Workflow:
1. Select an existing .sm file (created/managed with ArrowVortex).
2. Analyze the corresponding audio (audio_analyzer.py).
3. Run level generation scripts (Easy, Medium, Hard).
4. Run post-processing and graphics scripts.

This script does NOT modify timing, BPM or offset of the original file.
It only injects the notes generated by the level scripts.
"""

import os
import sys
import glob
import subprocess
import re

# Path Configuration
SRC_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SRC_DIR)
SONGS_FOLDER = os.path.join(ROOT_DIR, "songs")

def find_sm_file():
    """Finds the SM file in the songs folder by asking the user."""
    # Search for .sm files in songs/ and immediate subdirectories
    sm_files = []
    
    # Search in songs/
    sm_files.extend(glob.glob(os.path.join(SONGS_FOLDER, "*.sm")))

    # Search in subdirectories of songs/ (e.g. songs/Group/Song.sm)
    for item in os.listdir(SONGS_FOLDER):
        item_path = os.path.join(SONGS_FOLDER, item)
        if os.path.isdir(item_path):
            sm_files.extend(glob.glob(os.path.join(item_path, "*.sm")))
            
    sm_files = sorted(sm_files)
    
    if not sm_files:
        print(f"❌ No .sm file found in '{SONGS_FOLDER}'.")
        print("ℹ️  Create the file with ArrowVortex first or make sure it's in the songs folder.")
        return None

    print("\n📄 Available SM files:")
    print("-" * 60)
    for idx, sm_file in enumerate(sm_files, 1):
        # Show relative path to songs for brevity
        rel_path = os.path.relpath(sm_file, SONGS_FOLDER)
        print(f"   {idx}. {rel_path}")
    print("-" * 60)
    
    while True:
        try:
            choice = input("👉 Select the file number to process (0 to exit): ")
            choice_num = int(choice)
            if choice_num == 0:
                return None
            if 1 <= choice_num <= len(sm_files):
                selected = sm_files[choice_num - 1]
                print(f"✅ Selected: {selected}")
                return selected
            else:
                print("❌ Invalid number.")
        except ValueError:
            print("❌ Please enter a valid number.")

def get_music_filename(sm_path):
    """Reads the #MUSIC tag from the .sm file."""
    try:
        with open(sm_path, 'r', encoding='utf-8') as f:
            content = f.read()
        match = re.search(r"#MUSIC:([^;]*);", content, re.IGNORECASE)
        if match:
            return match.group(1).strip()
        return None
    except Exception as e:
        print(f"⚠️  Error reading #MUSIC from .sm: {e}")
        return None

def find_audio_file(sm_path, music_filename):
    """Searches for the audio file based on the .sm path and #MUSIC tag."""
    if not music_filename:
        return None
        
    sm_dir = os.path.dirname(sm_path)
    
    # 1. Search in the same folder as .sm
    local_path = os.path.join(sm_dir, music_filename)
    if os.path.exists(local_path):
        return local_path
        
    # 2. Search in songs root (legacy fallback)
    root_song_path = os.path.join(SONGS_FOLDER, music_filename)
    if os.path.exists(root_song_path):
        return root_song_path
        
    # 3. Search recursively in songs (last resort)
    for root, dirs, files in os.walk(SONGS_FOLDER):
        if music_filename in files:
            return os.path.join(root, music_filename)
            
    return None

def main():
    print("🚀 StepMania Generator v3.0 - Orchestrator Mode")
    print(f"📂 Working Directory: {ROOT_DIR}")
    
    # 1. Identifica File SM Target
    sm_path = None
    
    # Controllo argomenti da riga di comando
    for arg in sys.argv:
        if arg.lower().endswith(".sm") and os.path.exists(arg):
            sm_path = arg
            break
            
    if not sm_path:
        sm_path = find_sm_file()
        
    if not sm_path:
        print("👋 No file selected. Exiting.")
        sys.exit(0)
        
    # 2. Identify Audio File
    music_filename = get_music_filename(sm_path)
    if not music_filename:
        print("❌ #MUSIC tag not found or empty in the .sm file.")
        sys.exit(1)

    audio_path = find_audio_file(sm_path, music_filename)
    if not audio_path:
        print(f"❌ Audio file '{music_filename}' not found.")
        print("ℹ️  Make sure the audio file is in the same folder as the .sm file.")
        sys.exit(1)
        
    print(f"🎵 Audio: {os.path.basename(audio_path)}")
    print(f"📄 Chart: {os.path.basename(sm_path)}")
    
    # 3. Esegui Pipeline
    skip_analysis = "--skip-analysis" in sys.argv
    
    # PRELIMINARY SM FILE CLEANUP
    # Remove old charts and normalize the header to avoid corruption
    print("\n🧹 [0/4] SM File Normalization...")
    try:
        with open(sm_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Trova l'inizio delle note
        # Cerchiamo il primo #NOTES: per separare l'header
        match = re.search(r'(?=#NOTES:)', content, re.IGNORECASE)
        if match:
            header = content[:match.start()].strip()
            # If there are notes after, they get removed.
            print("   ⚠️  Removed pre-existing charts (will be regenerated).")
        else:
            # No notes found, assume it's all header
            header = content.strip()

        # Clean header from spurious comments (e.g. //-------)
        # Remove lines starting with // to prevent tags from ending after separators
        lines = header.split('\n')
        header = '\n'.join([L for L in lines if not L.strip().startswith('//')]).strip()
            
        # --- AUTO-FIX METADATA (Restored Logic) ---
        # Helper to find tag value in current header
        def get_tag_val(tag, text):
            m = re.search(fr"#{tag}:([^;]*);", text, re.IGNORECASE)
            return m.group(1).strip() if m else None

        def set_tag_val(tag, val, text):
            # If tag exists (even empty), replace value
            if re.search(fr"#{tag}:", text, re.IGNORECASE):
                return re.sub(fr"#{tag}:[^;]*;", f"#{tag}:{val};", text, flags=re.IGNORECASE)
            else:
                # If it doesn't exist, append at the end
                return text.strip() + f"\n#{tag}:{val};"

        # 1. Retrieve/Analyze TITLE and ARTIST
        curr_title = get_tag_val("TITLE", header)
        curr_artist = get_tag_val("ARTIST", header)
        curr_music = get_tag_val("MUSIC", header)

        new_title = curr_title
        new_artist = curr_artist

        # If missing or invalid, calculate from filename
        if not curr_title or curr_title.lower() == "unknown" or not curr_artist:
            print("   ⚠️  Missing or incomplete metadata. Attempting auto-fix...")
            
            base_name = ""
            if curr_music:
                base_name = os.path.splitext(curr_music)[0]
            else:
                base_name = os.path.splitext(os.path.basename(sm_path))[0]
            
            parts = base_name.split(' - ')
            calc_title = base_name
            calc_artist = "Unknown"
            
            if len(parts) >= 2:
                calc_title = parts[0].strip()
                calc_artist = parts[1].strip()
            
            if not curr_title or curr_title.lower() == "unknown":
                new_title = calc_title
                header = set_tag_val("TITLE", new_title, header)
                print(f"      🔹 Title set to: {new_title}")
                
            if not curr_artist:
                new_artist = calc_artist
                header = set_tag_val("ARTIST", new_artist, header)
                print(f"      🔹 Artist set to: {new_artist}")

        # 2. Complete list of standard tags with defaults

        # These tags MUST be in the .sm file for full compatibility
        default_tags = {
            "TITLE": new_title if new_title else "",
            "SUBTITLE": "",
            "ARTIST": new_artist if new_artist else "Unknown",
            "TITLETRANSLIT": "",
            "SUBTITLETRANSLIT": "",
            "ARTISTTRANSLIT": "",
            "GENRE": "",
            "CREDIT": "StepGenerator",
            "MUSIC": os.path.basename(audio_path) if audio_path else "",
            "BANNER": "",
            "BACKGROUND": "",
            "LYRICSPATH": "",
            "CDTITLE": "",
            "SAMPLESTART": "20.000", # Default sicuro
            "SAMPLELENGTH": "15.000",
            "SELECTABLE": "YES",
            "OFFSET": "0.000",
            "BPMS": "0.000=120.000", # Fallback se manca
            "STOPS": "",
            "DELAYS": "",
            "WARPS": "",
            "TIMESIGNATURES": "0.000=4=4",
            "TICKCOUNTS": "0.000=4",
            "COMBOS": "0.000=1",
            "SPEEDS": "0.000=1.000=0.000=0",
            "SCROLLS": "0.000=1.000",
            "FAKES": "",
            "LABELS": "0.000=Song Start",
            "BGCHANGES": "",
            "FGCHANGES": ""
        }

        # 3. Apply missing tags
        for tag, default_val in default_tags.items():
            curr_val = get_tag_val(tag, header)
            
            if curr_val is None:
                # Completely missing, add it
                header = set_tag_val(tag, default_val, header)
            elif curr_val == "" and tag in ["CREDIT", "SELECTABLE", "TIMESIGNATURES", "TICKCOUNTS", "COMBOS", "SPEEDS", "SCROLLS", "LABELS", "SAMPLESTART", "SAMPLELENGTH"]:
                # Present but empty, and we have a useful default, set it
                header = set_tag_val(tag, default_val, header)

        # SampleStart specific fix (if present but 0)
        curr_sample = get_tag_val("SAMPLESTART", header)
        try:
            if float(curr_sample) <= 0.001:
                 header = set_tag_val("SAMPLESTART", "20.000", header)
                 print("      🔹 SampleStart fixed to: 20.000")
        except:
             pass

        # SampleLength specific fix (if present but 0)
        curr_len = get_tag_val("SAMPLELENGTH", header)
        try:
            if not curr_len or float(curr_len) <= 0.001:
                 header = set_tag_val("SAMPLELENGTH", "15.000", header)
                 print("      🔹 SampleLength fixed to: 15.000")
        except:
             pass

        # ------------------------------------------

        # Make sure the header ends correctly
        if not header.endswith(';') and not header.strip() == "":
             header += ";"
             
        # Rewrite the file with only the cleaned and fixed header
        with open(sm_path, 'w', encoding='utf-8') as f:
            f.write(header + "\n")
            
        print("   ✅ Header normalized and corrected.")
        
    except Exception as e:
        print(f"   ❌ Error during normalization: {e}")
        # Don't block, try to continue
    
    # A. Audio Analysis
    if not skip_analysis:
        print("\n🎧 [1/4] Running Audio Analysis...")
        analyzer_script = os.path.join(SRC_DIR, "audio_analyzer.py")
        if os.path.exists(analyzer_script):
            try:
                subprocess.run([sys.executable, analyzer_script, audio_path, sm_path], check=True)
            except subprocess.CalledProcessError as e:
                print(f"❌ Audio analysis error: {e}")
                sys.exit(1)
        else:
            print(f"❌ Missing script: {analyzer_script}")
            sys.exit(1)
    else:
        print("\n⏭️  [1/4] Skipping Audio Analysis (Using existing analysis_data.json)")
        if not os.path.exists("analysis_data.json"):
            print("⚠️  Warning: analysis_data.json not found! Subsequent scripts may fail.")

    # B. Level Generation
    print("\n🎹 [2/4] Level Generation...")
    levels = [
        {
            "name": "Easy",
            "folder": os.path.join(ROOT_DIR, "1 easy"),
            "scripts": ["easy_4th.py", "easy_8th.py", "easy_jump.py", "easy_hold.py"]
        },
        {
            "name": "Medium",
            "folder": os.path.join(ROOT_DIR, "2 medium"),
            "scripts": ["medium_4th.py", "medium_8th.py", "medium_jump.py", "medium_hold.py"]
        },
        {
            "name": "Hard",
            "folder": os.path.join(ROOT_DIR, "3 hard"),
            "scripts": ["hard_4th.py", "hard_8th.py", "hard_jump.py", "hard_hold.py"]
        }
    ]
    
    analysis_file = "analysis_data.json"
    
    for level in levels:
        print(f"   🔹 Difficulty: {level['name']}")
        for script_name in level['scripts']:
            script_path = os.path.join(level['folder'], script_name)
            if os.path.exists(script_path):
                # print(f"      Running {script_name}...")
                try:
                    # Gli script di livello si aspettano: input_sm, output_sm, analysis_json
                    # Qui input e output sono lo stesso file (modifica in-place)
                    subprocess.run(
                        [sys.executable, script_path, sm_path, sm_path, analysis_file], 
                        check=True,
                        stdout=subprocess.DEVNULL, # Riduciamo il rumore in console
                        stderr=subprocess.PIPE     # Catturiamo errori se ci sono
                    )
                    print(f"      ✅ {script_name}")
                except subprocess.CalledProcessError as e:
                    print(f"      ❌ Error in {script_name}: {e.stderr.decode().strip()}")
            else:
                # Silent if script doesn't exist (maybe not all levels have all scripts)
                pass

    # C. Post Processing
    print("\n✨ [3/4] Post-Processing...")
    tail_refiners = ["PP_mute.py", "PP_IntroEnd.py"]
    for script_name in tail_refiners:
        script_path = os.path.join(SRC_DIR, script_name)
        if os.path.exists(script_path):
            try:
                subprocess.run([sys.executable, script_path, sm_path, sm_path, analysis_file], check=True)
                print(f"   ✅ {script_name}")
            except subprocess.CalledProcessError as e:
                print(f"   ❌ Error in {script_name}: {e}")

    # D. Graphics & Cleanup
    print("\n🖼️  [4/4] Graphics & Organization...")
    
    # Graphics
    gfx_script = os.path.join(SRC_DIR, "add_grafic.py")
    if os.path.exists(gfx_script):
        try:
            print("   Running add_grafic.py...")
            subprocess.run([sys.executable, gfx_script, sm_path], check=True)
        except subprocess.CalledProcessError:
            print("   ⚠️  Warning: Graphics generation error (non-critical).")

    # Final Actions
    final_script = os.path.join(SRC_DIR, "PP_azioniFinali.py")
    if os.path.exists(final_script):
        try:
            cmd = [sys.executable, final_script, sm_path]
            if skip_analysis:
                cmd.append("--preserve-json")
            subprocess.run(cmd, check=True)
            print("   ✅ Final organization completed.")
        except subprocess.CalledProcessError as e:
            print(f"   ❌ Final actions error: {e}")

    print("\n✅✅✅ PIPELINE COMPLETED SUCCESSFULLY! ✅✅✅")
    print(f"Processed file: {sm_path}")
    print("Remember to reload songs in StepMania!")

if __name__ == "__main__":
    main()
